In [37]:
import pandas as pd
import numpy as np
import os

In [2]:
import torch

In [4]:
# constructing first tensors
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [5]:
# PyTorch tensors and NumPy arrays are stored in contiguous memory blocks

In [6]:
# 
points = torch.zeros(6)
points[0] = 1.0
print(points)

tensor([1., 0., 0., 0., 0., 0.])


In [8]:
# can pass a Python list to the constructor to the same effect
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
print(points)

tensor([1., 4., 2., 1., 3., 5.])


In [10]:
# 2D-tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(points)

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])


In [11]:
# 
points.shape

torch.Size([3, 2])

In [13]:
#
points = torch.zeros(3, 2)
print(points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [15]:
#
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print(points)

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])


In [16]:
#
points[0, 1] # this is another tensor

tensor(4.)

In [17]:
# Tensors and storages
# Tensors are views over a storage instance
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [19]:
points.storage()[3]

1.0

In [21]:
# changeing the value of a storage changes the content of its referring tensor
points_storage = points.storage()

In [24]:
# 
points_storage[0] = 100.0

In [25]:
points

tensor([[100.,   4.],
        [  2.,   1.],
        [  3.,   5.]])

In [26]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [27]:
second_point

tensor([2., 1.])

In [28]:
torch.Size([2])

torch.Size([2])

In [31]:
points_t = points.t()
id(points.storage()) == id(points_t.storage()) # the tensor and its transpose share the storate

True

In [32]:
# Numeric types
# float 32
# float 64
# float 16
# ...

In [34]:
# indexing tensors
# some_list = list(range(6))
# 
points[1:] # all rows after first
points[1:,:] # all rows after first, all columns
points[1:, 0] # all rows after first, first column

tensor([2., 3.])

In [35]:
# advanced indexing
# numpy: its uniquity in the Python Data Science ecosystem, python array type
# zero-copy interoperability
# 
points = torch.ones(3, 4)
# 
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [36]:
# obtain a PyTorch tensor from a numpy array
# 
points = torch.from_numpy(points_np)

In [39]:
# Serializing tensors
torch.save(points, "./mypoints.t")

In [40]:
# os.listdir()

['mypoints.t',
 'PyTorchBasics.Rmd',
 '.ipynb_checkpoints',
 'Tensor Basics.ipynb']

In [41]:
# as an alternative, you can pass a file descriptor in lieu of the filename
with open("./mypoints2.t", "wb") as f:
    torch.save(points, f)

In [42]:
points = torch.load("./mypoints2.t")

In [44]:
# this is equivalent to 
with open('./mypoints.t','rb') as f:
    points = torch.load(f)

In [ ]:
# moving tensors to the GPU
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]], device = "cuda")
points_gpu = points.to(device="cuda")
# 

In [45]:
# tensor API
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1) # the first dimension to be transposed, the second dimension to be transposed


In [46]:
help(torch.transpose)

Help on built-in function transpose:

transpose(...)
    transpose(input, dim0, dim1) -> Tensor
    
    Returns a tensor that is a transposed version of :attr:`input`.
    The given dimensions :attr:`dim0` and :attr:`dim1` are swapped.
    
    The resulting :attr:`out` tensor shares it's underlying storage with the
    :attr:`input` tensor, so changing the content of one would change the content
    of the other.
    
    Args:
        input (Tensor): the input tensor.
        dim0 (int): the first dimension to be transposed
        dim1 (int): the second dimension to be transposed
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 1.0028, -0.9893,  0.5809],
                [-0.1669,  0.7299,  0.4942]])
        >>> torch.transpose(x, 0, 1)
        tensor([[ 1.0028, -0.1669],
                [-0.9893,  0.7299],
                [ 0.5809,  0.4942]])

